config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'
  get 'admin/table'
  get 'admin/receipt'
  devise_for :users
  get 'form', to: 'inspects#schedule_form'
  get 'show', to: 'inspects#show'
  post 'inspect_create', to: 'inspects#create'
  patch 'inspects/:id/change_status', to: 'admin#change_status', as: :change_status
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "inspects#schedule"
end

app/models/adition.rb
# == Schema Information
#
# Table name: aditions
#
#  id          :bigint           not null, primary key
#  body        :text
#  name        :string
#  price_cents :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  inspect_id  :bigint           not null
#
# Indexes
#
#  index_aditions_on_inspect_id  (inspect_id)
#
# Foreign Keys
#
#  fk_rails_...  (inspect_id => inspects.id)
#
class Adition < ApplicationRecord
  belongs_to :inspect
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inspect.rb
# == Schema Information
#
# Table name: inspects
#
#  id                :bigint           not null, primary key
#  body              :text
#  email             :string
#  end_date          :datetime
#  hash_finder       :string
#  phone             :string
#  revision_date     :datetime
#  revision_time     :string
#  status            :integer          default("requested")
#  status_updated_at :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  kind_id           :bigint           not null
#
# Indexes
#
#  index_inspects_on_kind_id  (kind_id)
#
# Foreign Keys
#
#  fk_rails_...  (kind_id => kinds.id)
#
class Inspect < ApplicationRecord
  belongs_to :kind
  has_many :aditions

  # Definición del enum para el status en inglés
  enum status: {
    requested: 0,
    received: 1,
    in_progress: 2,
    waiting_for_client: 3,
    finished: 4,
    canceled: 5
  }

  # Callbacks
  before_update :set_status_updated_at, if: :will_save_change_to_status?
  before_save :set_hash_finder
  after_update :set_end_date_if_finished, if: :saved_change_to_status?

  private

  # Método para actualizar el campo status_updated_at
  def set_status_updated_at
    self.status_updated_at = Time.current
  end

  # Método para actualizar el campo hash_finder
  def set_hash_finder
    return if hash_finder.present?
    self.hash_finder = SecureRandom.hex 9
  end

  # Método para establecer end_date cuando el estado sea finished
  def set_end_date_if_finished
    if status == "finished" && end_date.nil?
      self.end_date = Time.current
      save(validate: false) # Evita la validación al guardar para evitar un loop infinito
    end
  end
end

app/models/kind.rb
# == Schema Information
#
# Table name: kinds
#
#  id                   :bigint           not null, primary key
#  margin               :float
#  name                 :string
#  revision_price_cents :float
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
class Kind < ApplicationRecord
  monetize :revision_price_cents
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  is_superadmin          :boolean
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :inspects
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  STATUS_ORDER = %w[requested received in_progress waiting_for_client finished].freeze

  def dashboard
    @pending_inspects_count = Inspect.where(status: 0).count
    @finished_inspects_count = Inspect.where(status: 4)
                                      .where('extract(month from end_date) = ?', Time.current.month)
                                      .count
  end

  def table
    @inspects_by_status = Inspect.all.group_by(&:status)
  end

  def receipt
    @inspect = Inspect.find(params[:id])
    render layout: false
  end

  def kind
  end

  def create_kind
  end

  def edit_kind
  end

  def update_kind
  end

  def change_status
    @inspect = Inspect.find(params[:id])
    current_status_index = STATUS_ORDER.index(@inspect.status)

    if params[:status] == 'next'
      new_status_index = (current_status_index + 1) % STATUS_ORDER.size
    elsif params[:status] == 'previous'
      new_status_index = (current_status_index - 1 + STATUS_ORDER.size) % STATUS_ORDER.size
    else
      flash[:alert] = "Acción no válida"
      redirect_to admin_table_path and return
    end

    new_status = STATUS_ORDER[new_status_index]

    unless @inspect.update(status: new_status)
      flash[:alert] = "Error al actualizar el estado"
    end

    redirect_to admin_table_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inspects_controller.rb
class InspectsController < ApplicationController
  def schedule
  end

  def schedule_form
    @inspect = Inspect.new
    @times = {
      "08:00" => "08:00 AM",
      "08:30" => "08:30 AM",
      "09:00" => "09:00 AM",
      "09:30" => "09:30 AM",
      "10:00" => "10:00 AM",
      "10:30" => "10:30 AM",
      "11:00" => "11:00 AM",
      "11:30" => "11:30 AM",
      "12:00" => "12:00 PM",
      "12:30" => "12:30 PM",
      "13:00" => "01:00 PM",
      "13:30" => "01:30 PM",
      "14:00" => "02:00 PM",
      "14:30" => "02:30 PM",
      "15:00" => "03:00 PM",
      "15:30" => "03:30 PM",
      "16:00" => "04:00 PM",
      "16:30" => "04:30 PM",
      "17:00" => "05:00 PM",
      "17:30" => "05:30 PM",
      "18:00" => "06:00 PM"
    }
    @pre_filled_email = params[:email] || ""  # Captura el email de la URL
  end

  def create
    @inspect = Inspect.new(inspect_params)
    if @inspect.save
      flash[:notice] = 'La inspección se ha creado con éxito.' # Mensaje de éxito
      redirect_to root_path
    else
      render :schedule_form
    end
  end

  def show
    @inspect = Inspect.find_by(hash_finder: params[:hash_finder])
  end

  private

  # Define the inspect_params method
  def inspect_params
    params.require(:inspect).permit(:kind_id, :body, :email, :revision_date, :revision_time, :phone)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inspects_helper.rb
module InspectsHelper
end

app/views/admin/_navbar.html.erb
<!-- app/views/shared/_navbar.html.erb -->
<nav class="navbar navbar-expand-lg navbar-light bg-light px-4">
  <a class="navbar-brand" href="<%= root_path %>">MyApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Dashboard', admin_dashboard_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Tabla', admin_table_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/admin/dashboard.html.erb
<%= render 'admin/navbar' %>
<div class="container mt-5">
  <div class="row">
    <!-- Card for Pending Inspects -->
    <div class="col-md-6">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Inspecciones Pendientes</h5>
          <p class="card-text"><%= @pending_inspects_count %> inspecciones están pendientes</p>
        </div>
      </div>
    </div>

    <!-- Card for Finished Inspects in the Current Month -->
    <div class="col-md-6">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Inspecciones Finalizadas Este Mes</h5>
          <p class="card-text"><%= @finished_inspects_count %> inspecciones se finalizaron este mes</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/receipt.html.erb
  <div class="container">
    <div class="receipt-header">
      <h1>Recibo de Revisión</h1>
      <p>Fecha: <%= Time.now.strftime("%d/%m/%Y") %></p>
    </div>

    <div class="row mb-4">
      <div class="col-12">
        <h3>Datos del Cliente</h3>
        <p><strong>Nombre:</strong> <%= @inspect.email.split('@').first.capitalize %></p>
        <p><strong>Email:</strong> <%= @inspect.email %></p>
        <p><strong>Teléfono:</strong> <%= @inspect.phone %></p>
      </div>
    </div>

    <div class="row mb-4">
      <div class="col-12">
        <h3>Detalles de la Revisión</h3>
        <table class="table table-bordered details-table">
          <thead>
            <tr>
              <th>Elemento</th>
              <th>Descripción</th>
              <th>Fecha de Revisión</th>
              <th>Precio</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @inspect.kind.name %></td>
              <td><%= @inspect.body %></td>
              <td><%= @inspect.revision_date.strftime("%d/%m/%Y %I:%M %p") %></td>
              <td><%= number_to_currency(@inspect.kind.revision_price_cents * 5, unit: "$") %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <p class="total">Total: <%= number_to_currency(@inspect.kind.revision_price_cents * 5, unit: "$") %></p>
      </div>
    </div>

    <!-- Sección del código QR -->
    <div class="row qr-section">
      <div class="col-12">
        <h4>Información del Ticket</h4>
        <canvas id="qr-code"></canvas>
      </div>
    </div>

    <!-- Botón para imprimir -->
    <div class="row print-button">
      <div class="col-12">
        <button class="btn btn-primary" onclick="window.print()">Imprimir</button>
      </div>
    </div>
  </div>

  <!-- Script para generar el código QR -->
  <script src="https://cdn.jsdelivr.net/npm/qrious@4.0.2/dist/qrious.min.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      var qr = new QRious({
        element: document.getElementById('qr-code'),
        size: 150,
        value: "<%= number_to_currency(@inspect.kind.revision_price_cents / 100.0, unit: 'USD') %> <%= @inspect.revision_date.strftime('%d/%m/%Y') %> <%= @inspect.email %>"
      });
    });
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

app/views/admin/table.html.erb
<%= render 'admin/navbar' %>

<div class="mt-5">
  <div class="row flex-nowrap overflow-auto">
    <% Inspect.statuses.keys.each do |status| %>
      <div class="col-md-3 flex-shrink-0 m-2">
        <h4 class="text-center text-primary">
          <%= I18n.t("activerecord.attributes.inspect.statuses.#{status}") %>
        </h4>
        <div class="card border-secondary shadow-sm" style="min-height: 300px; min-width: 300px;">
          <div class="card-body p-3">
            <% @inspects_by_status[status.to_s]&.each do |inspect| %>
              <div class="card mb-3">
                <div class="card-header bg-light">
                  <h5 class="card-title text-dark">ID: <%= inspect.id %></h5>
                  <div>
                    <%= link_to '<i class="nf nf-md-file_document"></i> Recibo'.html_safe, admin_receipt_path(id: inspect.id), class: 'btn btn-info btn-sm me-2', target: '_blank' %>
                    <%= link_to '<i class="nf nf-md-account_multiple"></i> Seguimiento'.html_safe, show_path(hash_finder: inspect.hash_finder), class: 'btn btn-info btn-sm', target: '_blank' %>
                  </div>
                </div>
                <div class="card-body">
                  <ul class="list-unstyled mb-3">
                    <li><strong>Email:</strong> <%= inspect.email %></li>
                    <li><strong>Teléfono:</strong> <%= inspect.phone %></li>
                    <li><strong>Tipo:</strong> <%= inspect.kind.name %></li>
                    <li><strong>Descripción:</strong> <%= inspect.body %></li>
                    <li class="mt-4"><strong>Agenda:</strong> <%= inspect.revision_date.strftime('%d %b %Y') + " " + inspect.revision_time %></li>
                    <li class="mt-4"><strong>Última Actualización:</strong> <%= inspect.updated_at.strftime('%d %b %Y') %></li>
                  </ul>
                  <div class="d-flex justify-content-between">
                    <% unless inspect.status == 'requested' %>
                      <%= button_to '<i class="nf nf-md-arrow_left"></i>'.html_safe, 
                          change_status_path(inspect, status: 'previous'), 
                          method: :patch, class: 'btn btn-secondary btn-sm d-flex items-center' %>
                    <% end %>
                    <% unless inspect.status == 'finished' %>
                      <%= button_to '<i class="nf nf-md-arrow_right"></i>'.html_safe, 
                          change_status_path(inspect, status: 'next'), 
                          method: :patch, class: 'btn btn-success btn-sm d-flex items-center' %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/inspects/schedule.html.erb
<div class="container-fluid vh-100 position-relative">
  <div class="row h-100">
    <!-- Columna del Carrusel -->
    <div class="col-md-6 d-flex flex-column align-items-center justify-content-center bg-light position-relative">
      <!-- Imagen del Logotipo -->
      <div class="mb-4">
        <%= image_tag "logo.avif", alt: "Logotipo", class: "img-fluid", style: "min-height: 200px;" %>
      </div>

      <!-- Carrusel -->
      <div id="infoCarousel" class="carousel slide w-75" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="d-block w-100 text-center">
              <h3>Servicio de reparación a domicilio</h3>
              <p>Diagnóstico y solución rápida en cualquier tipo de equipo.</p>
            </div>
          </div>
          <div class="carousel-item">
            <div class="d-block w-100 text-center">
              <h3>Mantenimiento preventivo</h3>
              <p>Evita problemas mayores agendando constantemente nuestros servicios.</p>
            </div>
          </div>
          <div class="carousel-item">
            <div class="d-block w-100 text-center">
              <h3>Actualización de hardware y software</h3>
              <p>Mantén tu equipo actualizado con las últimas tecnologías.</p>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#infoCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Anterior</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#infoCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Siguiente</span>
        </button>
      </div>

      <!-- Botón debajo del Carrusel -->
      <div class="mt-4">
        <a href="https://evan674.wixsite.com/website" class="btn btn-primary btn-lg" target="_blank" rel="noopener noreferrer">
          Tienda
        </a>
      </div>
    </div>

    <!-- Columna del Formulario -->
    <div class="col-md-6 d-flex align-items-center justify-content-center bg-primary text-white">
      <div class="text-center">
        <h2>¡Agenda tu revisión ahora!</h2>
        <p>Deja tu correo y continua con el proceso.</p>
        <%= form_with url: form_path, method: :get, local: true do %>
          <div class="mb-3">
            <%= text_field_tag :email, nil, class: "form-control", placeholder: "Tu correo electrónico", required: true %>
          </div>
          <button type="submit" class="btn btn-light btn-lg">Agendar</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/inspects/schedule_form.html.erb
<div class="container h-100 d-flex justify-content-center align-items-center mt-5">
  <div class="row w-100">
    <div class="col-md-6 offset-md-3">
      <%= form_for @inspect, url: inspect_create_path, html: { class: 'p-4 border rounded bg-light shadow' } do |form| %>

        <!-- Error Messages (Optional) -->
        <% if @inspect.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(@inspect.errors.count, "error") %> prohibited this inspect from being saved:</h2>
            <ul>
              <% @inspect.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <!-- Kind (Select) -->
        <div class="mb-3">
          <%= form.label :kind_id, "Seleccionar Tipo", class: 'form-label' %>
          <%= form.collection_select :kind_id, Kind.all, :id, :name, { prompt: "Seleccione un dispositivo" }, { class: 'form-select' } %>
        </div>

        <!-- Body (Text Area) -->
        <div class="mb-3">
          <%= form.label :body, "Descripción del problema", class: 'form-label' %>
          <%= form.text_area :body, class: 'form-control' %>
        </div>

        <!-- Email (Input Field) -->
        <div class="mb-3">
          <%= form.label :email, "Correo", class: 'form-label' %>
          <%= form.email_field :email, class: 'form-control', value: @pre_filled_email %>
        </div>

        <!-- Phone (Input Field) -->
        <div class="mb-3">
          <%= form.label :phone, "Celular", class: 'form-label' %>
          <%= form.text_field :phone, class: 'form-control' %>
        </div>

        <!-- Revision Date (Date Picker) -->
        <div class="mb-3">
          <%= form.label :revision_date, "Fecha de revisión", class: 'form-label' %>
          <%= form.date_field :revision_date, class: 'form-control', min: (Date.current + 1).to_s, value: (Date.current + 1).to_s %>
        </div>


        <!-- Revision Time (Select) -->
        <div class="mb-3">
          <%= form.label :revision_time, "Hora de revisión", class: 'form-label' %>
          <%= form.select :revision_time, options_for_select(@times), { prompt: "Escoge la hora" }, { class: 'form-select' } %>
        </div>

        <!-- Submit Button -->
        <div class="text-center">
          <%= form.submit "Enviar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/inspects/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>Detalles de la Revisión</h4>
        </div>
        <div class="card-body">
          <div class="mb-3">
            <strong>Email:</strong>
            <p><%= @inspect.email %></p>
          </div>

          <div class="mb-3">
            <strong>Teléfono:</strong>
            <p><%= @inspect.phone %></p>
          </div>

          <div class="mb-3">
            <strong>Descripción:</strong>
            <p><%= @inspect.body %></p>
          </div>

          <div class="mb-3">
            <strong>Estado:</strong>
            <p><%= I18n.t("activerecord.attributes.inspect.statuses.#{@inspect.status}") %></p>
          </div>

          <div class="mb-3">
            <strong>Fecha de Revisión:</strong>
            <p><%= @inspect.revision_date&.strftime("%d/%m/%Y") %></p>
          </div>

          <div class="mb-3">
            <strong>Hora de Revisión:</strong>
            <p><%= @inspect.revision_time %></p>
          </div>

          <div class="mb-3">
            <strong>Fecha de Finalización:</strong>
            <p><%= @inspect.end_date&.strftime("%d/%m/%Y %H:%M:%S") %></p>
          </div>

          <div class="mb-3">
            <strong>Hash del Finder:</strong>
            <p><%= @inspect.hash_finder %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreTic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/journal/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://www.nerdfonts.com/assets/css/webfont.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- Mostrar mensajes flash -->
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>